apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresource.mysite.com
spec:
  scope: Namespaced
  group: mysite.com # api group
  names:
    kind: MyResource
    singular: myresource
    plural: myresources
    shortNames:
      - mr
  versions:
    - name: v1
      # this version is enabled in the REST API
      served: true
      # this is the version that should be used when persisting
      # custom resources to storage (there can be only one set to true)
      storage: true
      schema:
        openAPIV3Schema:
          # "Outer" "standard" k8s object with properties spec, apiVersion, kind, metadata and status. This nesting
          # inside the yaml file is just a waste of space as, for custom resource definitions, there can't be any other
          # "outer" type, nor can it have additional properties, nor can nothing else than spec be defined.
          type: object
          properties:
            spec:
              # the spec property contains the "inner" true custom definition
              type: object
              properties:
                var1:
                  type: string
                var2:
                  type: integer
