# deploy-nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    app: nginx-resolver
spec:
  containers:
    - name: nginx-resolver
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
spec:
  type: ClusterIP
  selector:
    app: nginx-resolver
  ports:
    - port: 80
      targetPort: 80
