apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "myTaint"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
