apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: my-gatewayClass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: my-gatewayClass
spec:
  # This must match the name expected by your controller (e.g., nginx.org/gateway-controller for NGINX)
  controllerName: nginx.org/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute # TLSRoute, TCPRoute, UDPRoute, GRPCRoute...
metadata:
  name: my-httpRoute
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /login
      backendRefs:
        - name: example-login-svc
          port: 8080
