# Daemons sets are like ReplicaSets, but they run one copy of the pod for each node.
# They are useful for monitoring agents. The kube-proxy agent for example can be deployed as a DaemonSet.
# From version 1.12, daemons use NodeAffinity and the default scheduler instead of nodeName to land to their nodes.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: monitoring-agent
          image: some-image
