# Gives a specific priority to a pod.
# Once created, associate the priority to a pod using the spec.priorityClassName property of the pod definition

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 10000
description: "An high priority"
preemptionPolicy: PreemptLowerPriority # What to do if a pod with higher priority comes in and low resources

# Use this command to check priorities of pods
# kubectl get pods -o custom-columns="NAME:.metadata.name,PRIORITY:.spec.priorityClassName"
