# The key difference between a "normal" volume and a PersistentVolume is their lifecycle and how they are managed:
# - A normal volume (like emptyDir or hostPath) is temporary and tied directly to the lifecycle of the Pod.
# - A Persistent Volume is a cluster resource independent from Pods. It's for durable, long-term storage.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Delete, Recycle (deprecated)
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
---
# An admin creates persistent volumes, an end user creates persistent volume claims to actually use them.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
