apiVersion: v1 # apps/v1 for ReplicaSet and deployment
kind: Pod # Service, ReplicaSet, Deployment, Namespace, ResourceQuota, ...
metadata:
  name: myapp-pod
  labels: # It's a dictionary. Labels are used to group resources together
    app: myapp
  annotations: # Additional data that may be useful for integration purposes
    buildVersion: "1.34"
spec:
  volumes:
    - name: shared-data-volume
      # hostPath is the simplest type of volume. It's for files inside the host filesystem.
      # There are a lot of providers for different cloud storage solutions.
      hostPath:
        path: /mnt/data
      # See what a PersistentVolume and a PersistentVolumeClaim are in persistent-volume.yaml
    - name: pvc-data-volume
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts: # where the volume is gonna be mounted inside the container
        - name: shared-data-volume
          mountPath: /data
        - name: pvc-data-volume
          mountPath: /pvc
