apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  # 1. Define the volume at the Pod level.
  volumes:
    # Give the volume a name so we can refer to it later.
    - name: secret-storage
      # Specify that this volume's source is a Secret.
      secret:
        # This MUST match the name of the Secret you created.
        secretName: my-app-secret

  # Define the container that will use the secret.
  containers:
    - name: my-app-container
      image: busybox
      # This command will keep the container running so we can inspect it.
      command: ["/bin/sh", "-c", "sleep 3600"]
      resources: {}
      # 2. Mount the volume into the container's filesystem.
      volumeMounts:
        - name: secret-storage # This MUST match the volume name from above.
          # The directory where the secret's data will appear as files.
          mountPath: "/etc/my-app/credentials"
          # It's a best practice to mount secrets as read-only.
          readOnly: true
