# A job executes a task only once when created and then reports its completion

apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
---
# A second apply to the same job.yaml would fail, so you need to use kubectl create each time,
# or use a cronjob with `suspend: true` as a template and then run
# kubectl apply -f cronjob-template.yaml; kubectl create job --from=cronjob/myjob-template my-manual-job-1

apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob-template
spec:
  schedule: "0 5 31 2 *" # impossible date, just to be sure
  suspend: true # <-- Fundamental part: never execute automatically
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-container
              image: busybox
              command: ["sh", "-c", "echo 'Compito eseguito!'; sleep 5"]
          restartPolicy: Never
