apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.mygroup.example.com
spec:
  group: mygroup.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 0
                  description: "Desired number of replicas"
              required: ["replicas"] # Make replicas required
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase of the resource"
                observedReplicas:
                  type: integer
                  description: "Actual number of ready replicas"
      # Enable the status subresource
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: myresources
    singular: myresource
    kind: MyResource
    shortNames:
      - mr
