apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secrets-provider
  labels:
    app: myapp
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-1:1234567890:secret:myapp/prod/secret-name-AbCdEf"
        objectType: "secretsmanager"

  # This part is crucial: it creates a native Kubernetes Secret (instead of directly mounting into the pod as a volume)
  secretObjects:
    - secretName: myapp-db-secret
      type: Opaque
      data:
        - objectName: "arn:aws:secretsmanager:eu-west-1:1234567890:secret:myapp/prod/secret-name-AbCdEf"
          key: database-creds # The key you want to use in the k8s Secret
